# Generated by Django 3.0.5 on 2020-05-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default='1234567890', max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.IntegerField(choices=[(0, 'SELECIONAR'), (1, 'Bolsa de trabajo UV'), (2, 'OCC Mundial'), (3, 'Buscotrabajo'), (4, 'Quierotrabajo')], default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
